name: flutter_clean_architecture_with_riverpod
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^3.0.3
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: ^3.0.3
  # https://pub.dev/packages/go_router
  go_router: ^16.2.4
  # https://pub.dev/packages/retrofit
  retrofit: ^4.7.3
  # https://pub.dev/packages/dio
  dio: ^5.9.0
  # https://pub.dev/packages/dio_http_formatter
  dio_http_formatter: ^3.3.1
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^3.1.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/intl
  intl: ^0.20.2
  # https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^9.2.4
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.2.1
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  retrofit_generator: ^10.0.6
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  flutter_gen_runner: ^5.12.0

dependency_overrides:
  analyzer: '>=7.7.1 <9.0.0'

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package